[project]
name = "img-archive"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pillow-jxl-plugin>=1.3.3",
    "trio>=0.30.0",
]

[dependency-groups]
dev = [
    "ruff>=0.12.0",
]
